### ISSUE TITLE
Modified Storage - Modified Refrigerator

### ISSUE THREAD

**Issue by Tellik** [Ktoblin/ONI-modes#1]
I'm seeing a bug where food stored in does not preserve. 

With it powered, food stored in it, I'm watching as the initial temperature drops down to 4C. However, freshness also keeps dropping with it at 4C and eventually the food will rot.

**Comment by Ktoblin** [comment]
> I'm seeing a bug where food stored in does not preserve.
> With it powered, food stored in it, I'm watching as the initial temperature drops down to 4C. However, freshness also keeps dropping with it at 4C and eventually the food will rot.

Thank you. 
I found a problem: food marked as "not cooled". All parameters and methods are the same as for the Refrigerator. Wiil dig deeper...

**Comment by Ktoblin** [comment]
Now food preserved.

**Comment by Tellik** [comment]
Hmmm. I'm guessing that Steam is failing lately. 

https://gyazo.com/f6374cc1f641d031766b479120deac89

I just removed the "new" Steam version, and installed the version from your github and it's working correctly.

https://gyazo.com/ba5a9eed72788c4234be97ee354f106e

It might be worth writing instructions in your github readme on how to manually install mods in case Steam is failing to update properly.
