### ISSUE TITLE
Updating SOlid sensors is justified, Klei's sensors are not a full replacement

### ISSUE THREAD

**Issue by Storm-Engineer** [Ktoblin/ONI-modes#3]
Greetings!

I posted on the Workshop but will say it here too: The sensors implemented by Klei only allow you to filter a single thing at a time, which is consistent with how gas and liquid sensors work, but:

1; Both gases and liquids have significantly fewer types than solids
2; Normally you only use one type of gas/liquid so you only want to filter one, but with solids it makes sense that you want to filter entire categories, eg all edibles. If I want to do that with the Klei filter that means I need nearly 30(!!!) sensor+shutoff pairs.

This the Klei sensors are not a true replacement for your mod, as your mod offers significantly better functionality and so it is justified to update it.

I suggest you rename it to "Advanced conveyor sensors" or similar and update its description to reflect that it offers advanced functionality compared to the Klei sensors.

**Comment by Ktoblin** [comment]
Updated and named "Advanced ...".
But make sure to use a temperature and desease sensors ceated by developers. May be I'll replace them in future.
